from __future__ import annotations

from dataclasses import dataclass

from pydantic import BaseModel

from .models import (
    BatchSortRequest,
    ConfigCreateRequest,
    ConfigFileDeleteRequest,
    ConfigPatchRequest,
    ConversationActivateRequest,
    ConversationCreateRequest,
    ConversationUpdateRequest,
    CronCreateRequest,
    CronUpdateRequest,
    InjectMessageRequest,
    KBSearchRequest,
    KBUploadUrlRequest,
    KnowledgeBaseCreateRequest,
    KnowledgeBaseUpdateRequest,
    MCPConnectionTestRequest,
    MCPServerCreateRequest,
    MCPServerUpdateRequest,
    MCPSyncProviderRequest,
    PersonaCreateRequest,
    PersonaFolderCreateRequest,
    PersonaFolderUpdateRequest,
    PersonaMoveRequest,
    PersonaUpdateRequest,
    PlatformConfigRequest,
    PluginBulkUpdateRequest,
    PluginConfigReplaceRequest,
    PluginInstallRepoRequest,
    PluginInstallZipRequest,
    PluginSourceSaveRequest,
    PluginUninstallRequest,
    PluginUpdateRequest,
    ProviderConfigRequest,
    ProviderSelectRequest,
    RenameRequest,
    SendLastMessageRequest,
    SendMessageRequest,
    SkillToggleRequest,
    SubagentConfigUpdateRequest,
    ToolInvokeRequest,
    ToolToggleRequest,
)


@dataclass(frozen=True, slots=True)
class EndpointDefinition:
    method: str
    path: str
    handler_name: str
    summary: str
    tags: tuple[str, ...]
    request_model: type[BaseModel] | None = None
    public: bool = False
    body_mode: str = "json"


ENDPOINTS: tuple[EndpointDefinition, ...] = (
    EndpointDefinition(
        "GET", "/health", "health", "Gateway health check", ("system",), public=True
    ),
    EndpointDefinition(
        "GET", "/meta", "meta", "Gateway metadata and subsystem summary", ("system",)
    ),
    EndpointDefinition(
        "POST",
        "/system/restart-core",
        "restart_core",
        "Restart AstrBot core process",
        ("system",),
    ),
    EndpointDefinition(
        "GET",
        "/platforms",
        "list_platforms",
        "List loaded platform instances",
        ("platforms",),
    ),
    EndpointDefinition(
        "GET",
        "/platforms/{platform_id}",
        "get_platform",
        "Get one loaded platform instance",
        ("platforms",),
    ),
    EndpointDefinition(
        "GET",
        "/platform-types",
        "list_platform_types",
        "List registered platform adapter types",
        ("platforms",),
    ),
    EndpointDefinition(
        "GET",
        "/platforms/stats",
        "platform_stats",
        "Get live platform status summary",
        ("platforms",),
    ),
    EndpointDefinition(
        "GET",
        "/platforms/stats/history",
        "platform_stats_history",
        "Get persisted platform traffic stats",
        ("platforms",),
    ),
    EndpointDefinition(
        "POST",
        "/platforms",
        "create_platform",
        "Create and load a platform config",
        ("platforms",),
        PlatformConfigRequest,
    ),
    EndpointDefinition(
        "PUT",
        "/platforms/{platform_id}",
        "update_platform",
        "Update and reload a platform config",
        ("platforms",),
        PlatformConfigRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/platforms/{platform_id}",
        "delete_platform",
        "Delete and terminate a platform config",
        ("platforms",),
    ),
    EndpointDefinition(
        "POST",
        "/platforms/{platform_id}/reload",
        "reload_platform",
        "Reload a platform instance",
        ("platforms",),
    ),
    EndpointDefinition(
        "POST",
        "/platforms/{platform_id}/enable",
        "enable_platform",
        "Enable a platform",
        ("platforms",),
    ),
    EndpointDefinition(
        "POST",
        "/platforms/{platform_id}/disable",
        "disable_platform",
        "Disable a platform",
        ("platforms",),
    ),
    EndpointDefinition(
        "GET", "/plugins", "list_plugins", "List plugin metadata", ("plugins",)
    ),
    EndpointDefinition(
        "GET", "/plugins/{plugin_name}", "get_plugin", "Get one plugin", ("plugins",)
    ),
    EndpointDefinition(
        "GET",
        "/plugins/market",
        "plugin_market_list",
        "List plugin market entries",
        ("plugins",),
    ),
    EndpointDefinition(
        "GET",
        "/plugins/readme/{plugin_name}",
        "get_plugin_readme",
        "Read plugin README",
        ("plugins",),
    ),
    EndpointDefinition(
        "GET",
        "/plugins/changelog/{plugin_name}",
        "get_plugin_changelog",
        "Read plugin changelog",
        ("plugins",),
    ),
    EndpointDefinition(
        "GET",
        "/plugins/sources",
        "get_plugin_sources",
        "Get custom plugin sources",
        ("plugins",),
    ),
    EndpointDefinition(
        "PUT",
        "/plugins/sources",
        "save_plugin_sources",
        "Save custom plugin sources",
        ("plugins",),
        PluginSourceSaveRequest,
    ),
    EndpointDefinition(
        "POST",
        "/plugins/install/repo",
        "install_plugin_repo",
        "Install plugin from repository URL",
        ("plugins",),
        PluginInstallRepoRequest,
    ),
    EndpointDefinition(
        "POST",
        "/plugins/install/zip",
        "install_plugin_zip",
        "Install plugin from local zip path",
        ("plugins",),
        PluginInstallZipRequest,
    ),
    EndpointDefinition(
        "POST",
        "/plugins/install/upload",
        "install_plugin_upload",
        "Install plugin from uploaded zip file",
        ("plugins",),
        body_mode="multipart",
    ),
    EndpointDefinition(
        "POST",
        "/plugins/reload",
        "reload_plugins",
        "Reload all plugins or one plugin",
        ("plugins",),
    ),
    EndpointDefinition(
        "POST",
        "/plugins/{plugin_name}/reload",
        "reload_plugin",
        "Reload a plugin",
        ("plugins",),
    ),
    EndpointDefinition(
        "POST",
        "/plugins/{plugin_name}/enable",
        "enable_plugin",
        "Enable a plugin",
        ("plugins",),
    ),
    EndpointDefinition(
        "POST",
        "/plugins/{plugin_name}/disable",
        "disable_plugin",
        "Disable a plugin",
        ("plugins",),
    ),
    EndpointDefinition(
        "POST",
        "/plugins/{plugin_name}/update",
        "update_plugin",
        "Update a plugin from its source",
        ("plugins",),
        PluginUpdateRequest,
    ),
    EndpointDefinition(
        "POST",
        "/plugins/update-all",
        "update_all_plugins",
        "Batch update plugins",
        ("plugins",),
        PluginBulkUpdateRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/plugins/{plugin_name}",
        "uninstall_plugin",
        "Uninstall a plugin",
        ("plugins",),
        PluginUninstallRequest,
    ),
    EndpointDefinition(
        "GET",
        "/configs/core",
        "get_core_config",
        "Get core config or a config node",
        ("configs",),
    ),
    EndpointDefinition(
        "PATCH",
        "/configs/core",
        "patch_core_config",
        "Patch core config by dotpath",
        ("configs",),
        ConfigPatchRequest,
    ),
    EndpointDefinition(
        "GET", "/configs/abconfs", "list_abconfs", "List abconf files", ("configs",)
    ),
    EndpointDefinition(
        "POST",
        "/configs/abconfs",
        "create_abconf",
        "Create an abconf file",
        ("configs",),
        ConfigCreateRequest,
    ),
    EndpointDefinition(
        "GET",
        "/configs/abconfs/{conf_id}",
        "get_abconf",
        "Get one abconf or a config node",
        ("configs",),
    ),
    EndpointDefinition(
        "PATCH",
        "/configs/abconfs/{conf_id}",
        "patch_abconf",
        "Patch an abconf by dotpath",
        ("configs",),
        ConfigPatchRequest,
    ),
    EndpointDefinition(
        "POST",
        "/configs/abconfs/{conf_id}/rename",
        "rename_abconf",
        "Rename an abconf",
        ("configs",),
        RenameRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/configs/abconfs/{conf_id}",
        "delete_abconf",
        "Delete an abconf",
        ("configs",),
    ),
    EndpointDefinition(
        "GET",
        "/configs/plugins",
        "list_plugin_configs",
        "List plugin configs",
        ("configs",),
    ),
    EndpointDefinition(
        "GET",
        "/configs/plugins/{plugin_name}",
        "get_plugin_config",
        "Get plugin config or a config node",
        ("configs",),
    ),
    EndpointDefinition(
        "PATCH",
        "/configs/plugins/{plugin_name}",
        "patch_plugin_config",
        "Patch plugin config by dotpath",
        ("configs",),
        ConfigPatchRequest,
    ),
    EndpointDefinition(
        "PUT",
        "/configs/plugins/{plugin_name}/full",
        "replace_plugin_config",
        "Replace plugin config with schema validation and reload",
        ("configs",),
        PluginConfigReplaceRequest,
    ),
    EndpointDefinition(
        "GET",
        "/configs/plugins/{plugin_name}/files",
        "list_plugin_config_files",
        "List plugin config files for a file-type config key",
        ("configs",),
    ),
    EndpointDefinition(
        "POST",
        "/configs/plugins/{plugin_name}/files/upload",
        "upload_plugin_config_files",
        "Upload files for a file-type plugin config key",
        ("configs",),
        body_mode="multipart",
    ),
    EndpointDefinition(
        "DELETE",
        "/configs/plugins/{plugin_name}/files",
        "delete_plugin_config_file",
        "Delete one plugin config file",
        ("configs",),
        ConfigFileDeleteRequest,
    ),
    EndpointDefinition(
        "GET",
        "/providers",
        "list_providers",
        "List loaded provider instances",
        ("providers",),
    ),
    EndpointDefinition(
        "GET",
        "/providers/{provider_id}",
        "get_provider",
        "Get one loaded provider instance",
        ("providers",),
    ),
    EndpointDefinition(
        "GET",
        "/provider-types",
        "list_provider_types",
        "List registered provider adapter types",
        ("providers",),
    ),
    EndpointDefinition(
        "GET",
        "/providers/current",
        "get_current_providers",
        "Get current provider selection",
        ("providers",),
    ),
    EndpointDefinition(
        "POST",
        "/providers/current",
        "set_current_provider",
        "Set current provider selection",
        ("providers",),
        ProviderSelectRequest,
    ),
    EndpointDefinition(
        "POST",
        "/providers",
        "create_provider",
        "Create and load a provider config",
        ("providers",),
        ProviderConfigRequest,
    ),
    EndpointDefinition(
        "PUT",
        "/providers/{provider_id}",
        "update_provider",
        "Update and reload a provider config",
        ("providers",),
        ProviderConfigRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/providers/{provider_id}",
        "delete_provider",
        "Delete a provider config",
        ("providers",),
    ),
    EndpointDefinition(
        "POST",
        "/providers/{provider_id}/reload",
        "reload_provider",
        "Reload a provider config",
        ("providers",),
    ),
    EndpointDefinition(
        "GET",
        "/providers/{provider_id}/models",
        "get_provider_models",
        "List available chat models for a provider",
        ("providers",),
    ),
    EndpointDefinition(
        "GET",
        "/messages/recent-sessions",
        "recent_sessions",
        "List recently observed sessions",
        ("messages",),
    ),
    EndpointDefinition(
        "POST",
        "/messages/send",
        "send_message",
        "Send a proactive message to a session",
        ("messages",),
        SendMessageRequest,
    ),
    EndpointDefinition(
        "POST",
        "/messages/send-last",
        "send_last_message",
        "Reply to the last observed session",
        ("messages",),
        SendLastMessageRequest,
    ),
    EndpointDefinition(
        "GET",
        "/messages/history",
        "message_history",
        "Get persisted platform message history",
        ("messages",),
    ),
    EndpointDefinition(
        "GET",
        "/logs/history",
        "log_history",
        "Get cached global logs with optional short watch",
        ("logs",),
    ),
    EndpointDefinition(
        "GET",
        "/logs/compact",
        "log_compact",
        "Get compact global logs for MCP or CLI usage",
        ("logs",),
    ),
    EndpointDefinition(
        "GET",
        "/logs/stream",
        "stream_logs",
        "Stream global logs over SSE",
        ("logs",),
    ),
    EndpointDefinition(
        "GET",
        "/logs/events/{event_id}",
        "event_logs",
        "Get logs related to one event or message id",
        ("logs",),
    ),
    EndpointDefinition(
        "GET",
        "/logs/events/{event_id}/stream",
        "stream_event_logs",
        "Stream logs related to one event or message id",
        ("logs",),
    ),
    EndpointDefinition(
        "GET",
        "/conversations",
        "list_conversations",
        "List conversations",
        ("conversations",),
    ),
    EndpointDefinition(
        "POST",
        "/conversations",
        "create_conversation",
        "Create a conversation",
        ("conversations",),
        ConversationCreateRequest,
    ),
    EndpointDefinition(
        "GET",
        "/conversations/{conversation_id}",
        "get_conversation",
        "Get one conversation",
        ("conversations",),
    ),
    EndpointDefinition(
        "PATCH",
        "/conversations/{conversation_id}",
        "update_conversation",
        "Update one conversation",
        ("conversations",),
        ConversationUpdateRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/conversations/{conversation_id}",
        "delete_conversation",
        "Delete one conversation",
        ("conversations",),
    ),
    EndpointDefinition(
        "POST",
        "/conversations/{conversation_id}/activate",
        "activate_conversation",
        "Set the current conversation for a session",
        ("conversations",),
        ConversationActivateRequest,
    ),
    EndpointDefinition(
        "GET",
        "/knowledge-bases",
        "list_kbs",
        "List knowledge bases",
        ("knowledge-bases",),
    ),
    EndpointDefinition(
        "POST",
        "/knowledge-bases",
        "create_kb",
        "Create a knowledge base",
        ("knowledge-bases",),
        KnowledgeBaseCreateRequest,
    ),
    EndpointDefinition(
        "GET",
        "/knowledge-bases/{kb_id}",
        "get_kb",
        "Get one knowledge base",
        ("knowledge-bases",),
    ),
    EndpointDefinition(
        "PATCH",
        "/knowledge-bases/{kb_id}",
        "update_kb",
        "Update one knowledge base",
        ("knowledge-bases",),
        KnowledgeBaseUpdateRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/knowledge-bases/{kb_id}",
        "delete_kb",
        "Delete one knowledge base",
        ("knowledge-bases",),
    ),
    EndpointDefinition(
        "GET",
        "/knowledge-bases/{kb_id}/documents",
        "list_kb_documents",
        "List knowledge base documents",
        ("knowledge-bases",),
    ),
    EndpointDefinition(
        "POST",
        "/knowledge-bases/search",
        "search_kb",
        "Search across knowledge bases",
        ("knowledge-bases",),
        KBSearchRequest,
    ),
    EndpointDefinition(
        "POST",
        "/knowledge-bases/{kb_id}/documents/url",
        "upload_kb_url",
        "Import a URL into a knowledge base",
        ("knowledge-bases",),
        KBUploadUrlRequest,
    ),
    EndpointDefinition(
        "GET", "/personas", "list_personas", "List personas", ("personas",)
    ),
    EndpointDefinition(
        "POST",
        "/personas",
        "create_persona",
        "Create a persona",
        ("personas",),
        PersonaCreateRequest,
    ),
    EndpointDefinition(
        "GET", "/personas/{persona_id}", "get_persona", "Get one persona", ("personas",)
    ),
    EndpointDefinition(
        "PATCH",
        "/personas/{persona_id}",
        "update_persona",
        "Update a persona",
        ("personas",),
        PersonaUpdateRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/personas/{persona_id}",
        "delete_persona",
        "Delete a persona",
        ("personas",),
    ),
    EndpointDefinition(
        "POST",
        "/personas/{persona_id}/move",
        "move_persona",
        "Move a persona to a folder",
        ("personas",),
        PersonaMoveRequest,
    ),
    EndpointDefinition(
        "GET",
        "/persona-folders",
        "list_persona_folders",
        "List persona folders",
        ("personas",),
    ),
    EndpointDefinition(
        "GET",
        "/persona-folders/tree",
        "persona_folder_tree",
        "Get persona folder tree",
        ("personas",),
    ),
    EndpointDefinition(
        "POST",
        "/persona-folders",
        "create_persona_folder",
        "Create a persona folder",
        ("personas",),
        PersonaFolderCreateRequest,
    ),
    EndpointDefinition(
        "PATCH",
        "/persona-folders/{folder_id}",
        "update_persona_folder",
        "Update a persona folder",
        ("personas",),
        PersonaFolderUpdateRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/persona-folders/{folder_id}",
        "delete_persona_folder",
        "Delete a persona folder",
        ("personas",),
    ),
    EndpointDefinition(
        "POST",
        "/personas/sort-order/batch",
        "batch_update_persona_sort_order",
        "Batch update persona and folder sort order",
        ("personas",),
        BatchSortRequest,
    ),
    EndpointDefinition(
        "GET", "/cron/jobs", "list_cron_jobs", "List cron jobs", ("cron",)
    ),
    EndpointDefinition(
        "GET", "/cron/jobs/{job_id}", "get_cron_job", "Get one cron job", ("cron",)
    ),
    EndpointDefinition(
        "POST",
        "/cron/jobs",
        "create_cron_job",
        "Create an active-agent cron job",
        ("cron",),
        CronCreateRequest,
    ),
    EndpointDefinition(
        "PATCH",
        "/cron/jobs/{job_id}",
        "update_cron_job",
        "Update a cron job",
        ("cron",),
        CronUpdateRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/cron/jobs/{job_id}",
        "delete_cron_job",
        "Delete a cron job",
        ("cron",),
    ),
    EndpointDefinition(
        "GET", "/tools", "list_tools", "List registered LLM tools", ("tools",)
    ),
    EndpointDefinition(
        "GET",
        "/tools/{tool_name}",
        "get_tool",
        "Get one registered LLM tool",
        ("tools",),
    ),
    EndpointDefinition(
        "POST",
        "/tools/{tool_name}/invoke",
        "invoke_tool",
        "Execute one registered LLM tool directly",
        ("tools",),
        ToolInvokeRequest,
    ),
    EndpointDefinition(
        "POST",
        "/tools/{tool_name}/toggle",
        "toggle_tool",
        "Enable or disable an LLM tool",
        ("tools",),
        ToolToggleRequest,
    ),
    EndpointDefinition(
        "GET",
        "/attachments/{attachment_id}/download",
        "download_attachment",
        "Download one attachment through the gateway",
        ("attachments",),
    ),
    EndpointDefinition(
        "GET",
        "/tools/mcp/servers",
        "list_mcp_servers",
        "List MCP server configs and loaded tools",
        ("tools",),
    ),
    EndpointDefinition(
        "POST",
        "/tools/mcp/servers",
        "add_mcp_server",
        "Add one MCP server",
        ("tools",),
        MCPServerCreateRequest,
    ),
    EndpointDefinition(
        "PUT",
        "/tools/mcp/servers/{server_name}",
        "update_mcp_server",
        "Update one MCP server",
        ("tools",),
        MCPServerUpdateRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/tools/mcp/servers/{server_name}",
        "delete_mcp_server",
        "Delete one MCP server",
        ("tools",),
    ),
    EndpointDefinition(
        "POST",
        "/tools/mcp/test",
        "test_mcp_connection",
        "Test an MCP server connection",
        ("tools",),
        MCPConnectionTestRequest,
    ),
    EndpointDefinition(
        "POST",
        "/tools/mcp/sync-provider",
        "sync_mcp_provider",
        "Sync MCP servers from a provider",
        ("tools",),
        MCPSyncProviderRequest,
    ),
    EndpointDefinition(
        "GET",
        "/subagents",
        "list_subagents",
        "List configured subagents",
        ("subagents",),
    ),
    EndpointDefinition(
        "GET",
        "/subagents/config",
        "get_subagent_config",
        "Get subagent orchestrator config",
        ("subagents",),
    ),
    EndpointDefinition(
        "PUT",
        "/subagents/config",
        "update_subagent_config",
        "Update subagent orchestrator config",
        ("subagents",),
        SubagentConfigUpdateRequest,
    ),
    EndpointDefinition(
        "GET",
        "/subagents/available-tools",
        "list_subagent_available_tools",
        "List tools that can be assigned to subagents",
        ("subagents",),
    ),
    EndpointDefinition(
        "GET", "/skills", "list_skills", "List installed skills", ("skills",)
    ),
    EndpointDefinition(
        "POST",
        "/skills/upload",
        "upload_skill",
        "Upload and install a skill zip",
        ("skills",),
        body_mode="multipart",
    ),
    EndpointDefinition(
        "POST",
        "/skills/{skill_name}/toggle",
        "toggle_skill",
        "Enable or disable a skill",
        ("skills",),
        SkillToggleRequest,
    ),
    EndpointDefinition(
        "DELETE",
        "/skills/{skill_name}",
        "delete_skill",
        "Delete one skill",
        ("skills",),
    ),
    EndpointDefinition(
        "POST",
        "/events/injections/message",
        "inject_message",
        "Inject a synthetic inbound message event",
        ("events",),
        InjectMessageRequest,
    ),
)


def collect_models() -> list[type[BaseModel]]:
    models: list[type[BaseModel]] = []
    for endpoint in ENDPOINTS:
        if endpoint.request_model and endpoint.request_model not in models:
            models.append(endpoint.request_model)
    return models


